### ISSUE TITLE
Feat: Support a fallback eth1 provider for beacon clients

### ISSUE THREAD

**Issue by yorickdowne** [rocket-pool/smartnode#113]
For those beacon clients that support this, offer an eth1 fallback provider. This is currently LH and Prysm.

- Query for fallback provider during `rocketpool service config` and store in $ETH1_FALLBACK_PROVIDER. If not provided by the user, use the same value as $ETH1_PROVIDER. This makes operations simple: If the user does not provide a fallback, the fallback is the primary, and the beacon will show both as failed when the primary fails.
-  Fallback options here could be querying for infura or alchemy ID, or "custom". If user is already using infura, that option should not be shown; geth should probably not be used as a fallback provider but only as primary.
- Change start-beacon.sh for LH: `--eth1-endpoints "$ETH1_PROVIDER,$ETH1_FALLBACK_PROVIDER"`
- Change start-beacon.sh for Prysm, by adding: `--fallback-web3provider "$ETH1_FALLBACK_PROVIDER"`.

While this can be done for an arbitrary number of fallbacks - two, three, many - offering just the one is probably plenty.

**Comment by darcius** [comment]
This is an excellent suggestion mate, we'll look at adding this to a future release no doubt.

**Comment by jclapis** [comment]
From a UX perspective, it might make sense to have the user select an eth2 client first during `service config`. That way, the config interview knows whether or not they selected a client that has fallback support, and can skip the question if it doesn't. Otherwise, they might enter the details for a fallback provider and get confused when it doesn't actually end up working because their eth2 client doesn't know what to do with it.

**Comment by jclapis** [comment]
Added in v1.2.0
