### ISSUE TITLE
Incremental exports fail due to df checks

### ISSUE THREAD

**Issue by jshufro** [rocket-pool/smartnode#230]
When a NO backs up their eth1 data to an external device, they should be able to do incremental backups due to the underlying utility being rsync.

However, smartnode does a `df` check on the device and errors out if there isn't enough free space:
```
Chain data size: 612 GiB Target dir free space: 321 GiB
Your target directory does not have enough space to hold the chain data. Please free up more space and try again.
```

We should add a flag to skip the `df` check

**Comment by javalasers** [comment]
It also seems that currently if `rocketpool service export-eth1-data` fails because of this failed df check, it still doesn't exit with an error return to the OS (so it doesn't look like an error if I include this within a shell script, for example). I may be scripting wrong. :-) But this is how it looks...

**Comment by 0xfornax** [comment]
I'll add a --force flag to ignore this check.

**Comment by jshufro** [comment]
you're a mensch
