### ISSUE TITLE
Timezone detection on installation fails to recognize correct timezone

### ISSUE THREAD

**Issue by superphiz** [rocket-pool/smartnode#249]
IIRC Timezone detection worked fine for a long time, but in the two most recent installations I've done it offers 'Etc/UTC' as the detected timezone while the correct timezone has an offset from UTC.

`rocketpool node register`

`Would you like to detect your timezone automatically? [y/n]`
`y`

`The detected timezone is 'Etc/UTC', would you like to register using this timezone? [y/n]`

**Comment by jclapis** [comment]
Timezone detection uses your IP's geolocation - if it can't reach the geolocation server or that server doesn't have your IP listed, it will show up as Etc/UTC as a catch-all.

**Comment by superphiz** [comment]
I'm offering a 250 USDC bounty to anyone who completes this issue with two solutions:
1. Better locale determination, mine is never picked up, it always shows "Etc/UTC". Ubuntu installers hit it perfectly every time and I like that.
2.  a listing of acceptable timezones that the user can choose from. The first dialog should show the continent, then the locales within that continent.

**Comment by 0xHodja** [comment]
#282 

Get request seems to fail on the current "https://freegeoip.app/json/" due to missing an API key.

Proposing solution to change from "https://freegeoip.app/json/" to a working API "https://ipinfo.io/json" which is public without requiring an API key.

Although this does not fulfil the second criteria, it should fix the majority of first-pass time zone location string issues.

**Comment by superphiz** [comment]
I'll pay 1/2 the bounty for this part of the job as soon as it gets merged. Thanks Hodja!

**Comment by sambacha** [comment]
> I'm offering a 250 USDC bounty to anyone who completes this issue with two solutions:
> 
> 1. Better locale determination, mine is never picked up, it always shows "Etc/UTC". Ubuntu installers hit it perfectly every time and I like that.
> 2. a listing of acceptable timezones that the user can choose from. The first dialog should show the continent, then the locales within that continent.

Configuring your locale can and does effect more than TZ, it can effect sorting, math, etc. 

Nodes should always be configured to UTC, since by definition UNIX epoch time is UTC.

Additionally if you are wanting to configure your locale and ignore the above, you must also configure your NTP pool connection information to whatever is the largest pool near your locale 


Also TZ can leak and reduce privacy

**Comment by 0xHodja** [comment]
> Configuring your locale can and does effect more than TZ, it can effect sorting, math, etc.
> 
> Nodes should always be configured to UTC, since by definition UNIX epoch time is UTC.
> 
> Additionally if you are wanting to configure your locale and ignore the above, you must also configure your NTP pool connection information to whatever is the largest pool near your locale
> 
> Also TZ can leak and reduce privacy

The promptTimezone() function being modified here only outputs a string. That string is then used in a tx to register the node on the eth network as appearing in a particular time zone.

The actual node time zone is not modified here in this function i.e. the user can set whatever they like, and it doesn't affect the actual node's time.

Fun fact: you can in fact set the time zone location to practically any graffiti string you want (e.g. "I_know_youre_snooping"), and then register that string with the RocketNodeManager (0x67CdE7AF920682A29fcfea1A179ef0f30F48Df3e) smart contract to confuse time zone parsers downstream that don't have error handling :)

![image](https://user-images.githubusercontent.com/119642880/210157719-ce0ea4a0-046a-4602-a338-5601298342d1.png)
