### ISSUE TITLE
Request: Change Nethermind setting in start-ec.sh script file

### ISSUE THREAD

**Issue by Bravedog74** [rocket-pool/smartnode#301]
Sync.AncientBodiesBarrier and Sync.AncientRecepitsBarrier is set to **1** in the start-ec.sh script file.  I need to update this every time a new smartnode stack is released.  Per Nethermind, you do not need to sync prior to 11052984.  Syncing from this barrier saves considerable sync time and drive space.

CMD="$PERF_PREFIX /nethermind/Nethermind.Runner \
        --config $NETHERMIND_NETWORK \
        --datadir /ethclient/nethermind \
        --JsonRpc.Enabled true \
        --JsonRpc.Host 0.0.0.0 \
        --JsonRpc.Port ${EC_HTTP_PORT:-8545} \
        --JsonRpc.EnginePort ${EC_ENGINE_PORT:-8551} \
        --JsonRpc.EngineHost 0.0.0.0 \
        --Sync.AncientBodiesBarrier **11052984** \
        --Sync.AncientReceiptsBarrier **11052984** \
        --Sync.SnapSync true \
        --Merge.Enabled true \
        --JsonRpc.JwtSecretFile=/secrets/jwtsecret \
        $EC_ADDITIONAL_FLAGS"

**Comment by jclapis** [comment]
This is the wrong repository - you actually want https://github.com/rocket-pool/smartnode-install/ .

Anyway, the problem with changing the `AncientBodiesBarrier` and `AncientReceiptsBarrier` to those values is that other Ethereum node operators can no longer sync from your node, because you don't have that chain state anymore. We intentionally set them to 1 to ensure that our node operators were being good citizens of the Ethereum network, and offered a complete chain history so others could sync from them. I've spoken to the Nethermind developers about this before, and have explained our position which they understood at the time - perhaps that has changed and I need to reach out to them again.

That being said, if you feel strongly about your stance then I suggest you put a post up in [our governance forum](https://dao.rocketpool.net). If the community agrees with you, then we can change it.
