### ISSUE TITLE
Feature Request: `rocketpool service prune` and `rocketpool service reset`

### ISSUE THREAD

**Issue by jshufro** [rocket-pool/smartnode#323]
Every now and then docker-ce screws up its persisted state and needs a light cleaning.

Typically this takes the form of `rocketpool service stop; docker system prune -ay; rocketpool service start`
Ideally we'd add this to smartnode, with `rocketpool service reset` doing the above.

Additionally, many NOs are not aware of the fact that old images are retained until `docker system prune -ay` is run, so a command called `rocketpool service prune` would be nice, but probably only if it can be done in a way that doesn't deleting the latest images/containers

**Comment by activescott** [comment]
FYI: Starting on this...

**Comment by activescott** [comment]
@jshufro `docker system prune` is pretty aggressive and will remove all containers. This is recoverable but likely involves GBs of downloads again by the user. That can could be fine, after all the user is asking for pretty serious action and maybe that's what ya'll do in support now and it's fine.

Another another option is to go through all container names that we know we need for the current smartnode stack (I believe they're in config) and tag them. As far as I know if we explicitly tag them they won't be removed by prune. After the prune, then I think we'd need to remove that tag we used so that they're cleaned up when the various image's rev their version in the future.

Preference? Thoughts?

**Comment by jshufro** [comment]
I think we'll want a `--all` option if we're going to preserve currently-used by default.

Mostly, this command will be used to rebuild rocketpool_net, which can only be deleted if all the _containers_ within are removed. Hopefully your solution preserving currently-used images doesn't prevent their containers from being deleted?

**Comment by activescott** [comment]
I added an --all option in the PR. Also rebased to current master. Careful with `--all` as it nukes your `rocketpool/smartnode           v1.11.9-dev` container on a dev machine and reset won't be able to start the node after the prune until you rebuild the daemon container :)
