### ISSUE TITLE
Auto-scale option or headless deposits

### ISSUE THREAD

**Issue by actuallymentor** [rocket-pool/smartnode#60]
Right now if a node wants to be maximally useful by offering a maximum number of minipools they need to:

1. Check if refunds are available (can be automated now with `grep`)
2. Run the refund command (can be automated now with piping)
3. Run the deposit command (can *not* be fully automated easily)

Both do not have a headless option. The first can be automated with piping since it is a one step process, but the second does not.

Ideally there should be a config option for autoscaling.

If that is too much work then a `rocketpool deposit 16 -y` that deposits 1 and accepts the network rate should suffice. Node operators can then check the refund status programatically and trigger the above command.

**Comment by moles1** [comment]
We discussed this concept internally but decided against implementing it for now due to the desired UX flow:

- We wanted node operators to perform refunds manually/explicitly to ensure that they know they are there and they can use the refunded ETH accordingly. If refunds are automated, some operators may be unaware that they are occurring and that the refunded ETH can be re-staked. (Note that this could have been included in the `node` daemon but was implemented as explicit API calls instead).

- We wanted deposits to only be performed manually due to the fluctuations in network commission rate. It seemed presumptuous that auto-scaling minipools would be desirable for node operators given that the commission rate could potentially drop and saddle them with a large number of minipools earning a low fee.

On the second point, the commission rate mechanics may change according to RPIP-003, so it's definitely worth consideration if that happens.

I'll leave this issue open to gauge whether others would like to see these features implemented - it seems likely that they should make it into a future release at some point :)

**Comment by actuallymentor** [comment]
Thanks for the thoughtful response!

> We wanted node operators to perform refunds manually/explicitly to ensure that they know they are there and they can use the refunded ETH accordingly.

Perhaps an automated option through the CLI for those of us who use more advanced scripting? I have a cron that checks resource utilisation and makes a calc to see if I want to withdraw and potentially restake.

> We wanted deposits to only be performed manually due to the fluctuations in network commission rate.

Similar response to the above. Maybe don't make it default, but the automation addicts like myself would love to at least be able to, even if it takes more work to set up.

**Comment by moles1** [comment]
All of the above sound like good additions. We've got some more urgent issues to tackle for now, but should be able to circle back to this at some point :)

**Comment by moles1** [comment]
Implemented (along with other non-interactive option flags) on branch https://github.com/rocket-pool/smartnode/compare/v0.0.7

**Comment by actuallymentor** [comment]
Sweet! Is this auto-documented and if not did you add it to the docs (or shall I)?
