### ISSUE TITLE
Add (ability to add) a static node list to geth

### ISSUE THREAD

**Issue by Deepcryptodive** [rocket-pool/smartnode#62]
In the Discord I noticed many users have trouble syncing their ETH1 Geth client.
A common issue is that they are unable to connect to peers.
e.g. ``peercount=0 tried=4 static=0``

Most likely this is due to not having UPnP enabled, or being blocked by their ISP (as is the case for me).
This seems to mainly affect the syncing of Geth, and not of the ETH2 clients.

**Proposal:** hardcode a list of nodes into geth OR allow users to add a list of static nodes to geth, as for example found here: https://gist.github.com/rfikki/77081600ddc8432520d3bb3a9f80a493

Alternatively, somehow allow access to the geth console, so users can add a bunch of peers via  ``admin.addPeer `` themselves.

This should make running a pool more accessible to people that sadly have to rely on ISPs that close down their routers.

Why not use Infura? Well, if you are running >25 validators, the daily 100k query limit is easily reached.

**Comment by moles1** [comment]
We probably won't implement UX flows for eth 1.0 & eth 2.0 client options with this degree of granularity, since it will open the floodgates for all sorts of feature requests and will likely be pretty painful / tedious to maintain.

If users have a need to modify the CLI flags for the clients outside of the standard config as per the above, they can manually modify the startup scripts to suit their needs. I've added documentation for this kind of customization here: https://rocket-pool.readthedocs.io/en/latest/smart-node/customization.html#customizing-eth-1-0-and-eth-2-0-client-options
