### ISSUE TITLE
How to stop staking?

### ISSUE THREAD

**Issue by actuallymentor** [rocket-pool/smartnode#65]
I [read the docs](https://rocket-pool.readthedocs.io/en/latest/smart-node/reference.html#miscellaneous-commands) but can't find a way to stop my node gracefully.

When running `rocketpool minipool dissolve` I get `No minipools can be dissolved`.

How does one dissolve minipools?

**Comment by moles1** [comment]
Dissolving minipools is just for minipools which are ready to launch but you want to back out and reclaim your deposited ETH rather than have them stake.

Performing voluntary exits is actually not implemented in all of the supported eth2 clients yet, so this functionality isn't available in RP yet either. It will be added once it exists in both Prysm and Lighthouse.
