### ISSUE TITLE
Clarify ethstats configuration

### ISSUE THREAD

**Issue by Neozaru** [rocket-pool/smartnode#70]
Hello,

I am installing and configuring rocketpool following this guide : https://medium.com/rocket-pool/rocket-pool-v2-5-beta-node-operators-guide-77859891766b

I am not familiar to ethstats. Hence when I get that prompt
```
Please enter the Ethstats Label (leave blank for none)
(optional - for reporting Eth 1.0 node status to ethstats.net)
```
I don't really know if the information I'll provide will be used to register me as a new account or log me in.
A quick research leads me to **ethstats-cli** https://github.com/Alethio/ethstats-cli which makes me think that I need to register using this CLI. However that leads me to wonder if **ethstats-cli** is already included in the smartnode Docker image, or if I need to run it separately.*

* I am aware that it is optional and meant to be used by those who already know what they are doing. However I think feedback is always good to give.

**Comment by moles1** [comment]
The mechanics of ethstats are fairly complicated and aren't really going to fit into a brief description in a command-line prompt. If a user is familiar with it and wants to use it, they will know what to do; if not, they can simply ignore it and move on. I'll see if there is somewhere appropriate in the docs to add more info since it doesn't really fit here.
